### ISSUE TITLE
SNSサービスの用語について

### ISSUE THREAD

**Issue by turtton** [ShuttlePub/document#4]
投稿についてNoteだったりPostだったり、リツイートがrenoteだったりboostだったりとサービスによって用語が色々あるわけなんですが、これについて混乱を招くと否定的な意見もあり、完全に独自みたいな感じを出してるturboって用語も嫌がられそうってわけで、なんか標準ワード的なのがあればそれにしたい
Threadsってその辺なんか良い風にしてた気もするんですが、商標とかあったら怖いのでmisskeyあたりのワードが良いのかなとか思ったりもしてる

https://github.com/ShuttlePub/document/blob/ed06e375644b26bb1e83ad6e89a8184026c95a2b/docs/shuttlepub-core/data-structure.md?plain=1#L49-L65

**Comment by HalsekiRaika** [comment]
これちょっと難しいよね…
個人的には用語が変わったところで、自分の解釈に合うような言葉に無意識的に置きかえてる人が多いように見えたからあんまり問題ないのかなって思ってたりするかな

**Comment by turtton** [comment]
ではここで「threads 用語」などとtwitterで検索すると、用語が難解であるって意見がめっちゃ出てくるんですよね
まあそういう人たちをふるいにかけるのもまた1つの手ですが、せめて他のAP実装サービスの人たちから「は？」ってなるようなネーミングは避けたいなと
改めてthreadsとAP内で定義されてるワードを見たら結構近いのかな？出来ればAP実装で命名されてるワードそのままにしたいと思ってます

**Comment by HalsekiRaika** [comment]
確かに既に定義されている仕様書に従えば文句はないね
その方針で行くのが良さそう

**Comment by turtton** [comment]
Mastodonのboost/Misskeyのrenoteに対応するAPのワードはAnnounceであることを知りめちゃくちゃ渋い顔になりました。
なんでやねん...
![image](https://github.com/ShuttlePub/document/assets/39013345/c85df08a-463c-41a1-88a6-e7a1b71ef6eb)

**Comment by turtton** [comment]
ムカつくのでrenoteにします。ほんとどういう経緯なのこれ
-> 301ba59
